### ISSUE TITLE
Heroku config:set error

### ISSUE THREAD

**Issue by blanzh** [volodymyrlut/heroku-node-telegram-bot#15]
heroku config:set TOKEN=SET HERE THE TOKEN YOU'VE GOT FROM THE BOTFATHER
> Error: Missing required flag:
>  »     -a, --app APP  app to run command against
>  »   See more help with --help

heroku config:set TOKEN=SET HERE THE TOKEN YOU'VE GOT FROM THE BOTFATHER -a appName

**Comment by volodymyrlut** [comment]
Well, you are right. I will update docs accordingly.

Thank you!

**Comment by volodymyrlut** [comment]
Sorry, I've just noticed that in the tutorial app is created via `heroku create` in the source folder, so if we are running `heroku config:set`, CLI will already know what's the app name.

Thank you again.
