### ISSUE TITLE
Setting environment variables using Windows OS.

### ISSUE THREAD

**Issue by cltai9145** [volodymyrlut/heroku-node-telegram-bot#2]
hi, i've updated node.js to the latest version, but got the following error when running npm run set_env command: 

![untitled](https://cloud.githubusercontent.com/assets/19759901/18576564/4682c1e2-7c15-11e6-8961-09d5e81a740b.png)

Failed at the heroku-node-telegram-bot@1.0.0 set_env script 'export $(cat .env | xargs)'.
Make sure you have the latest version of node.js and npm installed.
If you do, this is most likely a problem with the heroku-node-telegram-bot package,
not with npm itself.
Tell the author that this fails on your system:
export $(cat .env | xargs)

is there anything that i can do to get it run properly?

**Comment by volodymyrlut** [comment]
Hey, @cltai9145 
You are using Windows OS and the error is actually in your Command Prompt's output:

```
export is not recognized as internal or external command, operable program or batch file
```

The reason you see this error is in the README.md file:

```
npm run set_env runs export $(cat .env | xargs) which actually set key-value pairs from the .env file to the environment.
```

Windows OS don't have export commands to set environment variables.
What you need to do is to put environment variables into your Windows registry from .env file.
You can run something like `set KEY=VALUE` for each key-value pair from the .env file.
Here is a nice [stackoverflow question](http://superuser.com/questions/79612/setting-and-getting-windows-environment-variables-from-the-command-prompt) about setting env variables on Widows machines. 

Or you can run something like 
`SET >> .env`
to export all variables from the .env file
Report me if the last one works, then i'll add some "node run " scripts for Windows users.

**Comment by toggor** [comment]
Hi! Thanks for example. For Windows you can create something like:
env.cmd
```
@echo=off
SET NODE_ENV=development
SET TOKEN=your_token
```

And change accordingly strings in: 
package.json
```
"start": "node index.js",
"set_env": "env.cmd",
```

But remember to revert things back when pushing to heroku!

**Comment by volodymyrlut** [comment]
Hi, @toggor!
Thank you for example! I believe I could somehow make it work, because right now I am using Windows machine. Anyway, today I am all in my work, so If you have an spare hour, you could open a PR.

Thank you much, man!

If you do not have a time to do this, I will provide it tomorrow:)

@cltai9145 ^
