### ISSUE TITLE
heroku restart does not work

### ISSUE THREAD

**Issue by ChrisWongAtCUHK** [volodymyrlut/heroku-node-telegram-bot#8]
I have try to make a directory "src" and move index.js, bot.js, web.js. Then change the package.json. It does not work.

After a few try, only leave index.js in the root directory and let src keeps other js files would still make it works again.

**Comment by volodymyrlut** [comment]
Hello!

Sorry for being late here.

If you haven't resolved this issue since now, I can help you.

Can you send me an example of your updated `package.json`?

Thank you!

**Comment by ChrisWongAtCUHK** [comment]
Sorry for late reply. I think I have wrong scripts in package.json before. It works fine at this moment. Thank you.

**Comment by volodymyrlut** [comment]
@ChrisWongAtCUHK glad you've resolved your issue.
