### ISSUE TITLE
Unhandled rejection Error when I test the bot

### ISSUE THREAD

**Issue by shakir-abdo** [volodymyrlut/heroku-node-telegram-bot#9]
``` javascript
Unhandled rejection Error: 400 {"ok":false,"error_code":400,"description":"Bad Request: message text is empty"}
```
and the message is not empty
I test it yesterday and it was working fine, but today did not, 
so I downloaded the project again and start a new fresh bot, but it also didn't work

**Comment by volodymyrlut** [comment]
Ok, I see the problem. Investigating it.

**Comment by volodymyrlut** [comment]
@shakir-abdo resolved!

The problem was with the Telegram API wrapper I was relying on. Consider using this version: https://github.com/volodymyrlut/heroku-node-telegram-bot/releases/tag/1.0.3

**Comment by shakir-abdo** [comment]
Thanks Now working like a charm 😍
